brews:
  - description: "Rotating credentials."
    github:
      owner: chanzuckerberg
      name: homebrew-tap
    homepage: "https://github.com/chanzuckerberg/rotator"
    test: system "#{bin}/rotator --help"
dockers:
  - dockerfile: Dockerfile
    image_templates:
      - docker.pkg.github.com/chanzuckerberg/rotator/rotator:{{.Commit}}
      - docker.pkg.github.com/chanzuckerberg/rotator/rotator:{{.Version}}
      - docker.pkg.github.com/chanzuckerberg/rotator/rotator:latest
    extra_files:
      - .
env_files:
  github_token: ~/.config/goreleaser/github_token
